### ISSUE TITLE
t/03-no_config.t fails if Test::Exception is not installed

### ISSUE THREAD

**Issue by eserte** [byterock/mojolicious-plugin-authorization#10]
Statistical analysis: http://analysis.cpantesters.org/solved?distv=Mojolicious-Plugin-Authorization-1.04#qr%3A%28Can%27t%20locate%20\S%2Bpm%29

Probably the missing dependency should be declared as a prereq, or the test should be skipped if Test::Exception is not installed.

**Comment by eserte** [comment]
Also failing: t/04-full_fat_app.t if Test::Deep is not installed.
```
Can't locate Test/Deep.pm in @INC (you may need to install the Test::Deep module) (@INC contains: ...) at t/04-full_fat_app.t line 49.
BEGIN failed--compilation aborted at t/04-full_fat_app.t line 49.
t/04-full_fat_app.t ....... 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
```

**Comment by lindleyw** [comment]
This is still failing with a fresh install of Perl 5.26.1, using cpanm to install.

**Comment by byterock** [comment]
Yeah will have to write up a skip for that or alike maybe in the next few days
Cheers guys

**Comment by byterock** [comment]
sorry clicked the wrong button
